### ISSUE TITLE
Just asking

### ISSUE THREAD

**Issue by NikoGrano** [gnouffre/wot-clan-war-viewer#24]
Is there any active development anymore?

**Comment by SuperPommeDeTerre** [comment]
No, the main developer has decided to quit.
I have (partially) get its work merged into one of my project.
BTW, my project is stalled at the moment because of my lack of time available to work on it...

**Comment by NikoGrano** [comment]
Is that hosted somewhere?

https://github.com/SuperPommeDeTerre/WoTClanTool



I'm going to create clan management panel with my 5 professional php coder friends...

**Comment by NikoGrano** [comment]
@SuperPommeDeTerre  Seems like your repo code is little bit... ehh... complicated... Could you point me?

Also if you're interested about remaking, please feel free to tell me!

**Comment by SuperPommeDeTerre** [comment]
My app is hosted here : http://wot.pixbuf.net/wct/
But, as I early said, i'm very busy at this time. I'll make into it later maybe.
Feel free to use my code if it's usable to you !

**Comment by NikoGrano** [comment]
@SuperPommeDeTerre Thank you!
Just say a word and I will give you permissions to the repo.

In case if I need to copy something from your code, I will make sure you name is mentioned in contributors list. But anyways, your code is little..... a mess .... and I will be using MVC framework, so it might be a little bit work to convert it to MVC style.

Anyways, BIG thanks to you!
